"""Add company and user tables

Revision ID: 7d8c3a6361fd
Revises: 
Create Date: 2025-08-06 23:13:19.158210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8c3a6361fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for SQLite ###
op.create_table(
    'companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
)
op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)

op.create_table(
    'tables',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(), nullable=False)
)

op.create_table(
    'service_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('quantity_served', sa.Integer(), nullable=False),
    sa.Column('served_by', sa.String(), nullable=False),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id']),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id']),
    sa.PrimaryKeyConstraint('id')
)
op.create_index(op.f('ix_service_logs_id'), 'service_logs', ['id'], unique=False)

op.add_column('tables', sa.Column('name', sa.String(), nullable=False))
op.drop_column('tables', 'guests')
op.drop_column('tables', 'status')
op.drop_column('tables', 'courses_json')
op.drop_column('tables', 'number')
op.drop_column('tables', 'server')

# Add columns with server_default to avoid SQLite NOT NULL error
op.add_column('users', sa.Column('email', sa.String(), nullable=False, server_default='temp@example.com'))
op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False, server_default='temppassword'))
op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))

op.alter_column('users', 'username',
           existing_type=sa.VARCHAR(),
           nullable=False,
           server_default='tempuser')

op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])

op.drop_column('users', 'password_hash')
op.drop_column('users', 'role')

op.add_column('wines', sa.Column('varietal', sa.String(), nullable=True))
op.add_column('wines', sa.Column('notes', sa.String(), nullable=True))
op.alter_column('wines', 'name',
           existing_type=sa.VARCHAR(),
           nullable=False)
op.alter_column('wines', 'vintage',
           existing_type=sa.INTEGER(),
           type_=sa.String(),
           existing_nullable=True)
op.drop_column('wines', 'type')
op.drop_column('wines', 'producer')
op.drop_column('wines', 'stock')
op.drop_column('wines', 'price')
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('wines', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('wines', sa.Column('stock', sa.INTEGER(), nullable=True))
    op.add_column('wines', sa.Column('producer', sa.VARCHAR(), nullable=True))
    op.add_column('wines', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.alter_column('wines', 'vintage',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('wines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('wines', 'notes')
    op.drop_column('wines', 'varietal')

    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')

    op.add_column('tables', sa.Column('server', sa.VARCHAR(), nullable=True))
    op.add_column('tables', sa.Column('number', sa.INTEGER(), nullable=True))
    op.add_column('tables', sa.Column('courses_json', sa.VARCHAR(), nullable=True))
    op.add_column('tables', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('tables', sa.Column('guests', sa.INTEGER(), nullable=True))
    op.drop_column('tables', 'name')

    op.drop_index(op.f('ix_service_logs_id'), table_name='service_logs')
    op.drop_table('service_logs')

    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
