"""service table reuse + constraints

Revision ID: 4def63c4ef2b
Revises: 0001
Create Date: 2026-01-19 00:47:37.884851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4def63c4ef2b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_step_events', schema=None) as batch_op:
        batch_op.alter_column('actor_user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('service_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('turn', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_service_tables_status_updated')
        batch_op.create_index('ix_service_tables_company_date_status_updated', ['company_id', 'service_date', 'status', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tables_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tables_service_date'), ['service_date'], unique=False)
        batch_op.create_unique_constraint('uq_table_use_per_day', ['company_id', 'service_date', 'table_number', 'turn'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('service_tables', schema=None) as batch_op:
        batch_op.drop_constraint('uq_table_use_per_day', type_='unique')
        batch_op.drop_index(batch_op.f('ix_service_tables_service_date'))
        batch_op.drop_index(batch_op.f('ix_service_tables_company_id'))
        batch_op.drop_index('ix_service_tables_company_date_status_updated')
        batch_op.create_index('ix_service_tables_status_updated', ['status', 'updated_at'], unique=False)
        batch_op.drop_column('turn')
        batch_op.drop_column('service_date')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('service_step_events', schema=None) as batch_op:
        batch_op.alter_column('actor_user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
